- name: Install required packages
  yum:
    name: ["nrpe", "nagios-plugins-*"]
    state: present
    update_cache: yes

# Run check_nrpe on Nagios server but against this host
- name: Run check_nrpe from Nagios server
  shell: /usr/lib64/nagios/plugins/check_nrpe -H {{ inventory_hostname }}
  register: nrpe_status
  delegate_to: 10.30.48.52
  failed_when: false
  changed_when: false

- name: Configure NRPE based on connectivity
  template:
    src: "{{ nrpe_template }}"
    dest: "/etc/nagios/nrpe.cfg"
    owner: root
    group: root
    mode: '0640'
    backup: yes
  vars:
    nrpe_template: >-
      {{ 'nrpe.cfg.j2' if nrpe_status.stdout | default('') is regex('NRPE v')
         else 'nrpe_withoutn.j2' if nrpe_status.stdout | default('') is regex('CHECK_NRPE')
         else omit }}
  when: nrpe_template is defined
  diff: true
  notify: Restart NRPE


- name: Configure host template
  template:
    src: nagios.cfg.j2
    dest: "/etc/nagios/servers/{{ inventory_hostname }}.cfg"
    owner: nagios
    group: nagios
    mode: '0640'
    backup: yes
  diff: true
  delegate_to: 10.30.48.52
  notify: Reload Nagios
