- name: Install required packages
  yum:
    name: ["nrpe", "nagios-plugins-*"]
    state: present
    update_cache: yes

# Run check_nrpe on 52 but delegate from 96
- name: Run check_nrpe on nagios-server
  shell: /usr/lib64/nagios/plugins/check_nrpe -H {{ inventory_hostname }}
  register: nrpe_status
  delegate_to: 10.30.48.52
  failed_when: false
  changed_when: false

- name: Set NRPE status fact for use in this host 
  set_fact:
    nrpe_stdout: "{{ nrpe_status.stdout }}"
  when: nrpe_status.stdout is defined

- name: Configure NRPE template for valid response
  template:
    src: nrpe.cfg.j2
    dest: "/etc/nagios/nrpe.cfg"
    owner: root
    group: root
    mode: '0640'
    backup: yes
  when: nrpe_stdout is search("NRPE v")
  diff: true

- name: Configure NRPE template for error case
  template:
    src: nrpe_withoutn.j2
    dest: "/etc/nagios/nrpe_withoutn.cfg"
    owner: root
    group: root
    mode: '0640'
    backup: yes
  when: nrpe_stdout is search("CHECK_NRPE")
  diff: true
